export const categories = ["All books", "Fiction", "Design", "Business", "Science", "Biography"];

export const books = [
  { id: "quiet-geometry", title: "The Quiet Geometry", author: "Mara Ellison", category: "Fiction", format: "Hardcover", price: 28, rating: 4.8, reviews: 124, badge: "Editor’s pick", color: "clay", initials: "QG", stock: 8, description: "A luminous novel about memory, belonging, and the spaces we leave behind.", isbn: "978-1-4920-1001-7" },
  { id: "making-space", title: "Making Space", author: "Jon Bell", category: "Design", format: "Hardcover", price: 42, rating: 4.9, reviews: 89, badge: "New", color: "ink", initials: "MS", stock: 5, description: "A considered guide to creating rooms and objects that support a meaningful life.", isbn: "978-1-4920-1002-4" },
  { id: "good-work", title: "The Good Work", author: "Elena Park", category: "Business", format: "Paperback", price: 22, rating: 4.7, reviews: 216, badge: "Bestseller", color: "sage", initials: "GW", stock: 12, description: "Practical principles for building teams where clarity, craft, and care can thrive.", isbn: "978-1-4920-1003-1" },
  { id: "small-universe", title: "A Small Universe", author: "Dr. Noah Vale", category: "Science", format: "Hardcover", price: 32, rating: 4.6, reviews: 73, badge: "", color: "blue", initials: "SU", stock: 4, description: "An inviting journey from subatomic particles to the architecture of the cosmos.", isbn: "978-1-4920-1004-8" },
  { id: "north-star", title: "North Star", author: "Ada Mensah", category: "Biography", format: "Paperback", price: 19, rating: 4.8, reviews: 168, badge: "Reader favorite", color: "gold", initials: "NS", stock: 9, description: "The intimate story of an explorer who redrew maps—and her own sense of home.", isbn: "978-1-4920-1005-5" },
  { id: "after-rain", title: "After the Rain", author: "Sofia Laurent", category: "Fiction", format: "Paperback", price: 18, rating: 4.5, reviews: 94, badge: "", color: "rose", initials: "AR", stock: 7, description: "A tender, atmospheric story of friendship and second chances on the Atlantic coast.", isbn: "978-1-4920-1006-2" },
  { id: "human-scale", title: "At Human Scale", author: "Leo Ash", category: "Design", format: "Hardcover", price: 38, rating: 4.7, reviews: 61, badge: "New", color: "olive", initials: "HS", stock: 6, description: "How thoughtful design makes products, streets, and systems feel more humane.", isbn: "978-1-4920-1007-9" },
  { id: "clear-decisions", title: "Clear Decisions", author: "Priya Shah", category: "Business", format: "Paperback", price: 24, rating: 4.6, reviews: 132, badge: "", color: "plum", initials: "CD", stock: 10, description: "A calm framework for making consequential decisions without unnecessary complexity.", isbn: "978-1-4920-1008-6" }
];
